LadderRace:
  #dalam detik lakukan math nya jangan malas!! 300detik = 5menit
  knockback-stick-max-use: 2
  afterGameStopTeleportWinner: world

  allowpvp: false
  maxplayerwin: 1
  lamapermainan: 300
  countdownmulai: 15
  gate:
    block: WHITE_WOOL
    pos1:
      x: 0
      y: 0
      z: 0
    pos2:
      x: 0
      y: 0
      z: 0
  world:
    name: "uwu"
    uuid: uuid
  Spawn:
    x: 0
    y: 0
    z: 0
  GameArea:
    pos1:
      x: 0
      y: 0
      z: 0
    pos2:
      x: 0
      y: 0
      z: 0
  FinishArea:
    pos1:
      x: 0
      y: 0
      z: 0
    pos2:
      x: 0
      y: 0
      z: 0

Message:
  prefix: "&b&lVISANTARA &e&// &r"
  broadcast:
    playerstatewin: "%prefix% %player% just finish the race in %timer%"
    adminstartgame: "%prefix% admin just start a game!"
    adminstopgame: "%prefix% admin just stop a game!"
    countdown: "%prefix% game will start in %countdown%"
    gamestatestop: "%prefix% &cthe game just ended!!"
  player:
    playerstateplaying: "%prefix% message %player% message"
    playerstatewin: "%prefix% You'v win in %timer%"
    playerstatelose: "%prefix% You lose!!"
Scoreboard:
  tick: 1
  title: "LadderRace"
  scoreboard:
    - "Timer: %timer%"
    - "Winners: %winner%"